apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-kubeconform-config
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: manifest-validator
    app.kubernetes.io/component: config
data:
  KUBERNETES_VERSION: "1.28.0"
